version: '3.9'
services:
  db:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=secretroot'
      - 'MYSQL_DATABASE=umbragado'
      - 'MYSQL_USER=api'
      - 'MYSQL_PASSWORD=secretpassword'
    networks:
      - 'main'
networks:
  main:
    name: 'umbragado'
